# application.properties
app.cors.allowed-origins=http://13.61.175.245/

spring.application.name=HelpingHands

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://rushikeshkoli87400_db_user:usB9ljk6bMXrlv3D@cluster0.s9hg3cg.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=HelpingHands

management.endpoints.web.exposure.include=*
spring.thymeleaf.enabled=true

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080

# Cloudinary Configuration
cloudinary.cloud-name=dlj9xffro
cloudinary.api-key=226269671598645
cloudinary.api-secret=mU-kBicgp8Xc5bqMdT_rSwajM3I

# Stripe Configuration
stripe.api.key=your-stripe-api-key

# OpenAI Configuration
openai.api.key=your-openai-api-key

# reCAPTCHA Configuration
recaptcha.secret.key=6LeA8kQsAAAAAH1nvJ_RzhZHgkn-ZHRt_f6b3RDc
recaptcha.site.key=6LeA8kQsAAAAAH1nvJ_RzhZHgkn-ZHRt_f6b3RDc


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=helpinghandsngo26@gmail.com
spring.mail.password=allruxopjaztdlqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

